server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
    
version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
  ports:
    - 27969:27969
  volumes:
    - enviexpressdb:/enviexpressdb

volumes:
  enviexpressdb