server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 8082
    
version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - enviexpressdb:/enviexpressdb

volumes:
  enviexpressdb