#Configuracion de MongoDB
#spring.data.mongodb.host=localhost
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=visoftware
spring.data.mongodb.host=191.96.31.136
spring.data.mongodb.port=27017
spring.data.mongodb.database=enviexpressdb
spring.data.mongodb.uri=mongodb://admin:visoftware@191.96.31.136:27969/enviexpressdb?authSource=admin

#Server de la app
server.port=8080

# Propiedades de HttpClientConfiguration
admmodule.httpClient.connectTimeout: 30000 
admmodule.httpClient.readTimeout: 50000   

# Propiedades personalizadas
admmodule.credentials: username:password
