#Configuracion de MongoDB
spring.data.mongodb.host=191.96.31.136
spring.data.mongodb.port=27017
spring.data.mongodb.database=vimodulesdb
spring.data.mongodb.uri=mongodb://admin:visoftware@191.96.31.136:27969/vimodulesdb?authSource=admin

#Server de la app
server.port=8081

# Propiedades de HttpClientConfiguration
admmodule.httpClient.connectTimeout: 30000 
admmodule.httpClient.readTimeout: 50000   


